# Generated by Django 3.1.3 on 2021-08-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenapi', '0002_employee_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=50)),
                ('status', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'service_table',
            },
        ),
    ]
