# Generated by Django 3.2.5 on 2021-07-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
