# Generated by Django 3.1.3 on 2021-08-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenapi', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
